### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by clovis1122** [deinchapman/calculator#3]
Adding this so that we can participate in Hacktoberfest. I'll create issues and review PRs before they can be merged.

**Comment by shiv2077** [comment]
hey can you assign this to me

**Comment by deinchapman** [comment]
cool

**Comment by clovis1122** [comment]
👋 @shiv2077

Thank you for taking a look at this project. Please, feel free to look into the other Github issues that we have open.

**Comment by AnuragITrmlau** [comment]
Provide me the opportunity to execute this program and can can output better results

**Comment by AnuragITrmlau** [comment]
I am ready for it
