### ISSUE TITLE
Remove all but `main.py` file

### ISSUE THREAD

**Issue by clovis1122** [deinchapman/calculator#4]
We should unify all the current files into a single one. From what I saw in the other files, we need to unify `DecimalCalculator.py` and `RoundCalculator.py` into a single file, and remove the other file.

Perhaps we can ask at the very beginning of the calculator if the person wants to use decimals or floats. Remember the selection, and do calculations using it. We would, then, have different functions depending on whether we're using decimals or floats, and call them accordingly.

This would also be a good exercise for python classes and polymorphism, but in the first implementation, having different functions is just fine. We can, then, create another issue to explore a solution with classes and polymorphism.
 
The benefit of having a single entry point via the `main.py` file is that you will have a unified entry point for the application so that you can do `python main.py`  and it just works.

**Comment by deinchapman** [comment]
working on that

**Comment by Bakemono-san** [comment]
hi i would like to work on it can you assign me ?

**Comment by clovis1122** [comment]
👋 @Bakemono-san!

This one has already been assigned, but you can take a look at the other open issues. Do also feel free to create issues with improvements that we can do to the project!
