### ISSUE TITLE
Create README.md explaining how this project works 

### ISSUE THREAD

**Issue by clovis1122** [deinchapman/calculator#6]
This will help folks reading from the outside to understand the project & what it is about.

**Comment by deinchapman** [comment]
done it =)

**Comment by clovis1122** [comment]
I can't see the README.md file in this project... is it in a PR or somewhere else?

**Comment by deinchapman** [comment]
Oops. IM SORRY. 

as we are working with multiple projects i got confuse and created a readme for another project. 

but everything should be done tho.
